mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from machina.app import board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('personal.urls'),name='home'),
    path('', include('personal.urls')),
    path('accounts/dashboard/', include('dashboard.urls'),name='dashboard'),
    path('accounts/profile/', include('user.urls'),name='profile'),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include('appointment.urls'),name='appointment'),
    # Apps
    path('forum/', include(board.urls)),
    ]

user/urls.py
from django.urls import path
from django.urls import re_path
from django.urls import include
from .views import ProfileUpdate
from django.conf.urls import url
from .views import ProfileDetailView
from . import views

app_name='user'
urlpatterns = [
    path('', views.empty,name='profile_empty'),
    path('<int:id>/', ProfileDetailView.as_view(),name='profiledetail'),
    path('<int:id>/update', ProfileUpdate.as_view(),name='profileupdate')]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile_user")
    username = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50,blank=True)
    gender = models.TextField(max_length=10)
    status = models.CharField(max_length=10,default='activated')
    types = models.CharField(max_length=10)
    likes = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("user:profiledetail", kwargs={'id': self.user.id})

    def get_like_url(self):
        return reverse("appointment:like", kwargs={'id': self.user.id})

    def get_api_like_url(self):
        return reverse("appointment:like-api", kwargs={'id': self.user.id})

user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from appointment.models import Appointment
from decimal import Decimal

class SignupForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name', 'email', 'gender','types')

    # A custom method required to work with django-allauth, see https://stackoverflow.com/questions/12303478/how-to-customize-user-profile-when-using-django-allauth
    def signup(self, request, user):
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.save()
        # Save your profile
        final_rating=0
        profile = Profile()
        profile.user = user
        profile.gender = self.cleaned_data['gender']
        profile.types = self.cleaned_data['types']
        profile.save()

    def get_success_url(self):
        user_id = self.request.Profile.user.id # Get user_id from request
        return reverse_lazy('profiledetail', kwargs={'id': user_id})

user/views.py
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView
from .models import Profile
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseForbidden
from urllib import request
from django.core.exceptions import PermissionDenied

class ProfileUpdate(UpdateView):
    model = User
    fields=['first_name', 'last_name', 'email']
    template_name = 'profile/profile_update.html'

    def get_object(self):
        userid=self.kwargs.get('id')
        if userid==self.request.user.id:
            return get_object_or_404(User, id=userid)
        else:
            raise PermissionDenied

    def get_success_url(self):
        userid=self.kwargs.get('id')
        return reverse("user:profiledetail", kwargs={'id': userid})

class ProfileDetailView(DetailView):
    model = Profile
    fields=['first_name', 'last_name', 'email', 'gender','types']
    template_name = 'profile/profile.html'

    def get_object(self):
        userid=self.kwargs.get('id')
        if userid==self.request.user.id:
            return get_object_or_404(User, id=userid)
        else:
            raise PermissionDenied

def empty(request):
    return render(request, 'profile/profile_empty.html')

user/templates/profile/profile.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}
{% block content %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/profile.css' %}" type = "text/css"/>
{% endblock %}


<div class="inner-p">

  {% if user.is_authenticated %}
  <div class="profile">

    <div class="head">
      Profile for user
    </div>

    <h2>{{ object.username }}</h2>
    <p>Firstname: {{ object.first_name }}</p>
    <p>Lastname: {{ object.last_name }}</p>
    <p>Email address: {{ object.email }}</p>
    <p>Gender: {{ request.user.profile_user.gender }}</p>
    <p>Account Type: {{ request.user.profile_user.types }}</p>
    <a href="{% url 'user:profileupdate' object.id %}">I wish to change the profile</a>

  </div>


  {% else %}
  <center>
    <p>Sorry, You do not have rights to do that.</p>
  </center>
  {% endif %}
  {% endblock %}
</div>

user/templates/profile/profile_empty.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}
{% block content %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/profile.css' %}" type = "text/css"/>
{% endblock %}


<div class="inner-p">

  {% if user.is_authenticated %}
    <a href="{% url 'user:profiledetail' user.id %}">Check My Profile</a>
  {% else %}
  <center>
    <p>Sorry, You need to login first.</p>
    <p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
    <p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
  </center>
  {% endif %}
  {% endblock %}
</div>

user/templates/profile/profile_update.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}
{% block content %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/profile.css' %}" type = "text/css"/>
{% endblock %}


<div class="inner-p">
    {% if user.is_authenticated %}

    <center>
        <form method="post" class="profile">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
        <br>
        <a href="{% url 'user:profiledetail' user.id %}">I changed my mind, go back.</a>
    </center>
    {% else %}
    <center>
        <p>Sorry, You do not have rights to do that.</p>
    </center>
    {% endif %}
</div>
{% endblock %}