appointment/urls.py
from django.urls import path
from django.urls import include
from . import views
from .views import(
    DoctorProfileListView,
    DoctorProfileDetailView,
    AppointmentListView,
    AppointmentDetailView,
    DoctorAppointmentListView,
    DoctorAppointmentDetailView,
    DoctorAppointmentUpdateView,
    DoctorLikeRedirect,
    DoctorLikeAPI,
)

app_name='appointment'
urlpatterns = [
    path('', DoctorProfileListView.as_view(), name='Doctor_ListView'),
    path('<int:id>/', DoctorProfileDetailView.as_view(), name='Doctor_DetailView'),
    path('<int:id>/like', DoctorLikeRedirect.as_view(), name='like'),
    path('api/<int:id>/like', DoctorLikeAPI.as_view(), name='like-api'),
    path('history/', AppointmentListView.as_view(), name='Appointment_ListView'),
    path('history/<int:id>', AppointmentDetailView.as_view(), name='Appointment_DetailView'),
    path('make_appointment/', views.make_appointment, name='make_appointment'),
    path('handle_appointment/', DoctorAppointmentListView.as_view(), name='handle_appointment'),
    path('handle_appointment/<int:id>', DoctorAppointmentDetailView.as_view(), name='handle_appointment_detail'),
    path('handle_appointment/<int:id>/update', DoctorAppointmentUpdateView.as_view(), name='appointment_update'),]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from machina.app import board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('personal.urls'),name='home'),
    path('', include('personal.urls')),
    path('accounts/dashboard/', include('dashboard.urls'),name='dashboard'),
    path('accounts/profile/', include('user.urls'),name='profile'),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include('appointment.urls'),name='appointment'),
    # Apps
    path('forum/', include(board.urls)),
    ]

user/urls.py
from django.urls import path
from django.urls import re_path
from django.urls import include
from .views import ProfileUpdate
from django.conf.urls import url
from .views import ProfileDetailView
from . import views

app_name='user'
urlpatterns = [
    path('', views.empty,name='profile_empty'),
    path('<int:id>/', ProfileDetailView.as_view(),name='profiledetail'),
    path('<int:id>/update', ProfileUpdate.as_view(),name='profileupdate')]

appointment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Appointment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="patient_user")
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="doctor_user")
    apply_date=models.DateField(auto_now_add=True)
    symptom=models.CharField(max_length=500)
    preferred_time=models.DateField()
    status=models.CharField(max_length=10,default='pending')


    def __str__(self):
        return self.patient.username

    def get_absolute_url(self):
        return reverse("appointment:Appointment_DetailView", kwargs={'id':self.id})

appointment/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Appointment
from django.core.exceptions import ValidationError
import datetime


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('patient','doctor', 'symptom', 'preferred_time')

    # A custom method required to work with django-allauth, see https://stackoverflow.com/questions/12303478/how-to-customize-user-profile-when-using-django-allauth
    def signup(self, request, patient,doctor):
        patient.username = self.cleaned_data['patient']
        patient.save()
        doctor.username = self.cleaned_data['doctor']
        doctor.save()
        # Save your profile
        appointment = Appointment()
        appointment.patient = patient
        appointment.doctor = doctor
        appointment.symptom = self.cleaned_data['symptom']
        appointment.preferred_time = self.cleaned_data['preferred_time']
        print("here")
        appointment.save()

    def get_success_url(self):
        user_id = self.request.appointment.patient.id # Get user_id from request
        return reverse_lazy('appointment:Appointment_ListView', kwargs={'id': user_id})

appointment/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import RedirectView
from user.models import Profile
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Appointment
from django.shortcuts import render
from .forms import AppointmentForm
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from urllib import request
from decimal import Decimal

class DoctorProfileListView(ListView):
    queryset=User.objects.all()
    template_name = 'appointment/appointment.html'

class DoctorAppointmentListView(ListView):
    queryset=Appointment.objects.all()
    template_name = 'appointment/handle_appointment.html'

class DoctorProfileDetailView(DetailView):
    queryset=User.objects.all()
    template_name = 'appointment/appointment_detail.html'

    def get_object(self):
        userid= self.kwargs.get("id")
        return get_object_or_404(User, id=userid)

class DoctorLikeRedirect(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        doctorid=self.kwargs.get("id")
        obj=get_object_or_404(User, id=doctorid)
        current_user=self.request.user
        if current_user.is_authenticated:
            if current_user in obj.profile_user.likes.all():
                obj.profile_user.likes.remove(current_user)
            else:
                obj.profile_user.likes.add(current_user)
        return reverse("appointment:Doctor_DetailView", kwargs={'id': doctorid})

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from rest_framework.permissions import IsAuthenticated


class DoctorLikeAPI(APIView):
    """
    View to list all users in the system.

    * Requires token authentication.
    * Only admin users are able to access this view.
    """
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, id=None, format=None):
        #doctorid=self.kwargs.get("id")
        obj=get_object_or_404(User, id=id)
        current_user=self.request.user
        updated=False
        liked=False
        if current_user.is_authenticated:
            if current_user in obj.profile_user.likes.all():
                liked=False
                obj.profile_user.likes.remove(current_user)
            else:
                liked=True
                obj.profile_user.likes.add(current_user)
            updated=True
        data={
            "updated": updated,
            "liked": liked
        }
        return Response(data)


class DoctorAppointmentUpdateView(UpdateView):
    model = Appointment
    fields=['status']
    template_name = 'appointment/appointment_update.html'

    def get_object(self):
        appointmentid=self.kwargs.get('id')
        userid=self.request.user.id
        appointment_model = Appointment.objects.get(id=appointmentid)
        if appointment_model.doctor.id==userid:
            return get_object_or_404(Appointment, id=appointmentid)
        else:
            raise PermissionDenied


    def get_success_url(self):
        return reverse("appointment:handle_appointment")

class DoctorAppointmentDetailView(DetailView):
    queryset=Appointment.objects.all()
    template_name = 'appointment/handle_appointment_detail.html'

    def get_object(self):
        appointmentid= self.kwargs.get("id")
        return get_object_or_404(Appointment, id=appointmentid)

class AppointmentListView(ListView):
    queryset=Appointment.objects.all()
    template_name = 'appointment/appointment_history.html'

class AppointmentDetailView(DetailView):
    queryset=Appointment.objects.all()
    template_name = 'appointment/appointment_history_detail.html'

    def get_object(self):
        appointmentid=self.kwargs.get('id')
        userid=self.request.user.id
        appointment_model = Appointment.objects.get(id=appointmentid)
        if appointment_model.patient.id==userid:
            return get_object_or_404(Appointment, id=appointmentid)
        else:
            raise PermissionDenied


def make_appointment(request):
    doctors = Profile.objects.filter(types="Doctor")
    if request.method == 'post' or request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('appointment:Appointment_ListView') )
    else:
        form = AppointmentForm()
    return render(request, 'appointment/make_appointment.html', {'doctors':doctors,'form': form})

appointment/templates/appointment/appointment.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}


{% block content %}
{% if user.is_authenticated %}
<center>
  {% if request.user.profile_user.types == "Doctor" %}
    <h3>These functions are not designed for the Doctor type user, you can try</h3>
    <a href="{% url 'appointment:handle_appointment' %}">Check pending appointment</a>
      {% else %}
  <h3>Please select the doctor from the following list if you want to apply an appointment:</h3>
  <p><a href="{% url 'appointment:Appointment_ListView' %}">Click here to see your appointment history</a><p>
  <br>
  {% for instance in object_list %}
  {% if instance.profile_user.types == "Doctor" %}
    <div class="item">
      <p>User id: {{ instance.id }} - <a href="{% url 'appointment:Doctor_DetailView' instance.id %}">{{instance.username}}</a> - {{ instance.profile_user.likes.count }}</p>
    </div>
  {% endif %}
  {% endfor %}
    {% endif %}
</center>
{% else %}
<center>
<p>Sorry, You need to login first.</p>
<p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
<p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
</center>
{% endif %}
{% endblock %}

appointment/templates/appointment/appointment_detail.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block content %}
{% if user.is_authenticated %}
{% include 'base/js.html' %}
<script>
$(document).ready(function(){
          function updateText(btn, newCount, verb){
          btn.text(newCount + " " + verb)
          btn.attr("data-likes", newCount)
      }
      $(".like-btn").click(function(e){
        e.preventDefault()
        var this_ = $(this)
        var likeUrl = this_.attr("data-href")
        var likeCount = parseInt(this_.attr("data-likes")) | 0
        var addLike = likeCount + 1
        var removeLike = likeCount - 1
        if (likeUrl){
           $.ajax({
            url: likeUrl,
            method: "GET",
            data: {},
            success: function(data){
              console.log(data)
              var newLikes;
              if (data.liked){
                  updateText(this_, addLike, "Unlike")
              } else {
                  updateText(this_, removeLike, "Like")
                  // remove one like
              }
            }, error: function(error){
              console.log(error)
              console.log("error")
            }
          })
        }
      })
  })
</script>

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}

<center>
  <div class="info">

    <h3>Username: {{ object.username }}</h3>
    <p>Firstname: {{ object.first_name }}</p>
    <p>Lastname: {{ object.last_name }}</p>
    <p>Email: {{ object.email }}</p>
    <p>Gender: {{ object.profile_user.gender }}</p>
    <p>User Type: {{ object.profile_user.types }} </p>
    <p>Click to Like or Unlike this doctor: <a class='like-btn' data-href='{{ object.profile_user.get_api_like_url }}'
      data-likes='{{ object.profile_user.likes.count }}'
      href='{{ object.profile_user.get_like_url }}'>{{ object.profile_user.likes.count }} Like</a></p>
    <a href="{% url 'appointment:make_appointment' %}"> I wish to apply appointment to this doctor</a>
    <br>
    <br>
    <a href="{% url 'appointment:Appointment_ListView' %}">Go back</a>
  </div>
</center>
{% else %}
<center>
<p>Sorry, You do not have rights to do that.</p>
</center>
{% endif %}
<script>
$(document).ready(function(){
   {% block jquery %}{% endblock %}
 })
</script>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

appointment/templates/appointment/appointment_history.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}
{% block content %}
  <div class="inner-a">

    {% if user.is_authenticated %}

      <div class="head">
        <h3>The followings are your appointment history:</h3>
      </div>

      <div class="pending">
        <div class="head">
          <h4>Pending appointment:</h4>
        </div>
        <div class="content">
          {% for instance in object_list %}
          {% if instance.patient.username == user.get_username and instance.status == "pending" %}
          <div class="item">
            <p><a href="{% url 'appointment:Appointment_DetailView' instance.id %}">Your appointment number: {{ instance.id }}</a>
            <p>Applied on: {{instance.apply_date}}</p>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="accepted">
        <div class="head">
          <h4>Accepted Appointment:</h4>
        </div>
        <div class="content">
          {% for instance in object_list %}
          {% if instance.patient.username == user.get_username and instance.status == "accepted" %}
          <div class="item">
            <p><a href="{% url 'appointment:Appointment_DetailView' instance.id %}">Your appointment number: {{ instance.id }}</a>
            <p>Applied on: {{instance.apply_date}}</p>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="completed">
        <div class="head">
          <h4>Completed appointment:</h4>
        </div>
        <div class="content">
          {% for instance in object_list %}
          {% if instance.patient.username == user.get_username and instance.status == "completed" %}
          <div class="item">
            <p><a href="{% url 'appointment:Appointment_DetailView' instance.id %}">Your appointment number: {{ instance.id }}</a>
            <p>Applied on: {{instance.apply_date}}</p>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="completed">
        <div class="head">
          <h4>Denied appointment:</h4>
        </div>
        <div class="content">
          {% for instance in object_list %}
          {% if instance.patient.username == user.get_username and instance.status == "denied" %}
          <div class="item">
            <p><a href="{% url 'appointment:Appointment_DetailView' instance.id %}">Your appointment number: {{ instance.id }}</a>
            <p>Applied on: {{instance.apply_date}}</p>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>

      <a href="{% url 'appointment:Doctor_ListView' %}">Go Back</a>


    {% else %}
      <center>
        <p>Sorry, You need to login first.</p>
        <p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
        <p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
      </center>
    {% endif %}
  </div>
{% endblock %}

appointment/templates/appointment/appointment_history_detail.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
<div class="info">
  {% if user.is_authenticated %}
  <center>
    {% if object.patient.username == user.get_username %}
    <h3>Appointment ID: {{ object.id }}</h3>
    <p>Doctor name: <a href="{% url 'appointment:Doctor_DetailView' object.doctor.id %}">{{ object.doctor.get_username }}</a>(Click to see the Doctor profile)</p>
    <p>Patient name(You): {{ object.patient.get_username }}</p>
    <p>Date when applied: {{ object.apply_date }}</p>
    <p>Symptom: {{ object.symptom }}</p>
    <p>Preferred Time: {{ object.preferred_time }}</p>
    <p>Current status: {{ object.status }} </p>
    {% if object.status == "completed" %}
      {% endif %}
    <br>
    <br>
    <a href="{% url 'appointment:Appointment_ListView' %}">Go back</a>
    {% else %}
    <h3>You are not allowed to see other patients' appointment!</h3>
    {% endif %}

  </center>
</div>
{% else %}
<center>
<p>Sorry, You need to login first.</p>
<p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
<p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
</center>
{% endif %}
{% endblock %}

appointment/templates/appointment/appointment_update.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class="info">
  <center>
    <form method="post">{% csrf_token %}
      <p>Status:
        <select name="status">
           <option value="accepted">Accepted</option>
           <option value="denied">Denied</option>
           <option value="pending" selected>Pending</option>
           <option value="completed" >Completed</option>
         </select>
      </p>
      <input type="submit" value="Update">
  </form>
  <br>
  <a href="{% url 'appointment:handle_appointment'  %}">I changed my mind, go back.</a>
  </center>

</div>
{% else %}
<center>
<p>Sorry, You do not have rights to do that.</p>
</center>
{% endif %}
{% endblock %}

appointment/templates/appointment/handle_appointment.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}

<div class="inner-a">
  {% if user.is_authenticated %}
  <center>
    {% if request.user.profile_user.types == "Patient" %}
      <h3>These functions are not designed for the Doctor type user, you can try</h3>
      <a href="{% url 'appointment:Doctor_ListView' %}">Go back</a>
        {% else %}
    <h3>Please select the pending appointment from the following list</h3>

    <div class="pending">
      <div class="head">
        <h4>Pending appointment:</h4>
      </div>
      <div class="content">
        {% for instance in object_list %}
        {% if instance.doctor.id == user.id and instance.status == 'pending' %}
        <div class="item">
          <p><a href="{% url 'appointment:handle_appointment_detail' instance.id %}">{{ instance.patient.get_username }} applied an appointment to you at {{ instance.apply_date }}</a></p>

          <p>Applied on: {{instance.apply_date}}</p>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="accepted">
      <div class="head">
        <h4>Accepted Appointment:</h4>
      </div>
      <div class="content">
        {% for instance in object_list %}
        {% if instance.doctor.id == user.id and instance.status == 'accepted' %}
        <div class="item">
          <p><a href="{% url 'appointment:handle_appointment_detail' instance.id %}">{{ instance.patient.get_username }} applied an appointment to you at {{ instance.apply_date }}</a></p>
          <p>Applied on: {{instance.apply_date}}</p>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="completed">
      <div class="head">
        <h4>Completed appointment:</h4>
      </div>
      <div class="content">
        {% for instance in object_list %}
        {% if instance.doctor.id == user.id and instance.status == 'completed' %}
        <div class="item">
          <p><a href="{% url 'appointment:handle_appointment_detail' instance.id %}">{{ instance.patient.get_username }} applied an appointment to you at {{ instance.apply_date }}</a></p>
          <p>Applied on: {{instance.apply_date}}</p>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

    <div class="completed">
      <div class="head">
        <h4>Denied appointment:</h4>
      </div>
      <div class="content">
        {% for instance in object_list %}
        {% if instance.doctor.id == user.id and instance.status == 'denied' %}
        <div class="item">
          <p><a href="{% url 'appointment:handle_appointment_detail' instance.id %}">{{ instance.patient.get_username }} applied an appointment to you at {{ instance.apply_date }}</a></p>
          <p>Applied on: {{instance.apply_date}}</p>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>

  </center>
</div>
{% else %}
<center>
<p>Sorry, You need to login first.</p>
<p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
<p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
</center>
{% endif %}
{% endblock %}

appointment/templates/appointment/handle_appointment_detail.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="info">
  <center>
    <h3>Patient name: {{ object.patient.username }}</h3>
    <p>Patient Firstname: {{ object.patient.first_name }}</p>
    <p>Patient Lastname: {{ object.patient.last_name }}</p>
    <p>Apply Date: {{ object.apply_date }}</p>
    <p>Syptoms: {{ object.symptom }}</p>
    <p>Preferred Time: {{ object.preferred_time }}</p>
    <p>Current Status: {{ object.status }} </p>
    <br>
    {% if object.status == "completed" %}
    <a href="{% url 'appointment:handle_appointment' %}">Go back</a>
    {% else %}
      <a href="{% url 'appointment:appointment_update' object.id %}">I wish to update the appointment</a>
    <br>
    <a href="{% url 'appointment:handle_appointment' %}">Go back</a>
  </center>
  {% endif %}
</div>
{% else %}
<center>
<p>Sorry, You do not have rights to do that.</p>
</center>
{% endif %}
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

appointment/templates/appointment/make_appointment.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}

{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/app.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="info">
  <center>
    {% if request.user.profile_user.types == "Doctor" %}
      <h3>Doctor type users cannot apply appointment, sorry.</h3>
      <a href="{% url 'appointment:Doctor_ListView' %}">Go back</a>
        {% else %}
    <h3>Please fill in the form to apply an appointment</h3>
    <form method="post">
      {% csrf_token %}
      <label for="id_patient"></label>
      <input name="patient" value={{user.id}} type="hidden" id="id_patient">

      <div class="input-group">
        <label for="id_doctor">Doctor:</label>
        <select name="doctor" required="" id="id_doctor">

          <option value="">---------</option>
          {% for instance in doctors %}
          <option value="{{ instance.user.id }}">{{ instance.user.get_username }}</option>
          {% endfor %}

        </select>
      </div>

      <div class="input-group">
        <label for="id_symptom">Symptom:</label>
        <textarea type="text" name="symptom" maxlength="500" required="" id="id_symptom"></textarea>
      </div>

      <div class="input-group">
        <label for="id_preferred_time">Preferred time:</label>
        <input type="date" name="preferred_time" required="" id="id_preferred_time">
      </div>

      <button type="submit">Submit</button>
    </form>
  </center>
  {% endif %}
</div>
{% else %}
<center>
<p>Sorry, You need to login first.</p>
<p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
<p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
</center>
{% endif %}
{% endblock %}