dashboard/urls.py
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from machina.app import board

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('personal.urls'),name='home'),
    path('', include('personal.urls')),
    path('accounts/dashboard/', include('dashboard.urls'),name='dashboard'),
    path('accounts/profile/', include('user.urls'),name='profile'),
    path('accounts/', include('allauth.urls')),
    path('appointment/', include('appointment.urls'),name='appointment'),
    # Apps
    path('forum/', include(board.urls)),
    ]

user/urls.py
from django.urls import path
from django.urls import re_path
from django.urls import include
from .views import ProfileUpdate
from django.conf.urls import url
from .views import ProfileDetailView
from . import views

app_name='user'
urlpatterns = [
    path('', views.empty,name='profile_empty'),
    path('<int:id>/', ProfileDetailView.as_view(),name='profiledetail'),
    path('<int:id>/update', ProfileUpdate.as_view(),name='profileupdate')]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse

def dashboard(request):
    return render(request, 'dashboard/dashboard_home.html')

dashboard/templates/dashboard/dashboard_home.html
{% extends "personal/base.html" %}
{% load staticfiles%}
{% load i18n %}
{% load account socialaccount %}


{% block css %}
<link rel="stylesheet" href="{% static 'personal/css/dashboard.css' %}" type = "text/css"/>
{% endblock %}


{% block content %}
<div class="inner-d">

  {% if user.is_authenticated %}

  <div class="item">
    <img src="{% static 'personal/img/profile2.png' %}" alt="">
    <a href="{% url 'user:profiledetail' user.id %}">My Profile</a>
  </div>

  <div class="item">
    <img src="{% static 'personal/img/forum.png' %}" alt="">
    <a href="/forum">Forum</a>
  </div>

  <div class="item">
    <img src="{% static 'personal/img/appointment.png' %}" alt="">
    <a href="/appointment">My Appointment</a>
  </div>

  <div class="item">
    <img src="{% static 'personal/img/logout.png' %}" alt="">
    <a href="/accounts/logout">Logout</a>
  </div>

  {% else %}
  <center>
    <p>Sorry, You need to login first.</p>
    <p>Already have an account? Then please <a href="/accounts/login">Login</a>.</p>
    <p>Do not have an account yet? Then please <a href="/accounts/signup">Sign up</a>.</p>
  </center>
  {% endif %}

</div>
{% endblock %}